### ISSUE TITLE
Ready for new usergroups?

### ISSUE THREAD

**Issue by bhaugen** [vientos/vientos-deploy#14]
We have some requests for an app from some local nodes in FairCoop in Europe that Vientos might fit very well.

Do you think it is ready for another user group and deployment? Would the Vientos maintainers welcome something like that? They might want some help and might raise issues, etc, although mostly they will have their own installation and sysadmin team and possibly even a coder. And definitely translators.

Or are you happier keeping this as a more local-to-Mexico software? If so, no problems, no complaints.

**Comment by elf-pavlik** [comment]
Hi @bhaugen I think everyone should feel free and encouraged to give this software a try. We will change our deployment now to use [LXD](https://linuxcontainers.org/lxd/introduction/) which might slightly affect this repository.

Last week I (together with few neighbors) got 5km wireless bridge to near by town working and we start having reliable internet connection again. This way I will have possibility to respond to issues raised with just the timezone difference delay.

**Comment by elf-pavlik** [comment]
today/tomorrow i will update this repo with ansible playbook which will fully automate the deployment process

**Comment by elf-pavlik** [comment]
playbook works with `common.env: staging`, i still should document this part how env relates to names of branches in used repositories.
if something doesn't work please create specific issues
